server.port: 8082

spring:
  application:
    name: movie-service

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

security:
  basic:
    enabled: false
